# Generated by Django 2.0.3 on 2018-03-27 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=20)),
                ('state', models.SmallIntegerField(default=1)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('pwd', models.CharField(default='123456', max_length=32)),
                ('state', models.SmallIntegerField(default=1)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
