# Generated by Django 2.0.3 on 2018-03-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoDemo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(to='DjangoDemo.Role'),
        ),
    ]
