# Generated by Django 2.0.3 on 2018-03-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoDemo', '0002_auto_20180327_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roles',
            new_name='role',
        ),
    ]
